// Narration with two layers:
//   1. Pre-rendered neural voice clips (voices/*.ogg, generated by the
//      generate-voices.yml workflow with Piper) - warm, human, consistent.
//   2. Web Speech fallback for any line without a clip, using the least
//      robotic male en-GB voice the device has.
// Profiles: narrator (teaching), alien (weird characters), sound (slow,
// isolated phonic sounds). Clips are keyed by fnv1a-32 of `profile|text`,
// matching tools/gen-voice-manifest.mjs.

import { isMuted } from './audio.js';

const PREFERRED_MALE = [
  // "Natural" neural voices first - hugely less robotic where available
  'Microsoft Ryan Online (Natural) - English (United Kingdom)',
  'Microsoft Thomas Online (Natural) - English (United Kingdom)',
  'Microsoft Alfie Online (Natural) - English (United Kingdom)',
  'Google UK English Male',
  'Microsoft Ryan - English (United Kingdom)',
  'Microsoft George - English (United Kingdom)',
  'Microsoft George',
  'Daniel (English (United Kingdom))',
  'Daniel',
];

const PROFILES = {
  narrator: { pitch: 1.05, rate: 0.85 },
  alien: { pitch: 1.85, rate: 1.15 },
  // for isolated phonic sounds: very slow so nothing gets mangled
  sound: { pitch: 1.0, rate: 0.5 },
};

let chosenVoice = null;
let queue = [];
let speaking = false;
let bank = null; // manifest: hash -> { t, p }; a hash present = clip exists
const player = typeof Audio !== 'undefined' ? new Audio() : null;

function fnv(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

function pickVoice() {
  if (!('speechSynthesis' in window)) return;
  const voices = window.speechSynthesis.getVoices();
  if (!voices.length) return;
  const gb = voices.filter((v) => v.lang === 'en-GB');
  chosenVoice =
    voices.find((v) => PREFERRED_MALE.includes(v.name)) ||
    gb.find((v) => /natural/i.test(v.name) && !/female|sonia|libby|maisie|hollie|olivia|abbi|bella/i.test(v.name)) ||
    gb.find((v) => /male|daniel|george|ryan|arthur|oliver|brian/i.test(v.name) && !/female/i.test(v.name)) ||
    gb.find((v) => !/female|hazel|susan|libby|sonia|woman/i.test(v.name)) ||
    gb[0] ||
    voices.find((v) => v.lang.startsWith('en')) ||
    voices[0];
}

export function initSpeech() {
  if ('speechSynthesis' in window) {
    pickVoice();
    window.speechSynthesis.onvoiceschanged = pickVoice;
  }
  // Load the pre-rendered clip bank (absent until CI has generated it)
  fetch('../voices/manifest.json')
    .then((r) => (r.ok ? r.json() : null))
    .then((m) => { bank = m; })
    .catch(() => { /* no bank - fall back to Web Speech */ });
}

function speakTTS(text, profile, done) {
  if (!('speechSynthesis' in window)) { done(); return; }
  const u = new SpeechSynthesisUtterance(text);
  u.lang = 'en-GB';
  if (chosenVoice) u.voice = chosenVoice;
  const p = PROFILES[profile] || PROFILES.narrator;
  u.rate = p.rate;
  u.pitch = p.pitch;
  u.onend = done;
  u.onerror = done;
  try {
    window.speechSynthesis.speak(u);
  } catch {
    done();
  }
}

function pump() {
  if (speaking || !queue.length) return;
  const { text, profile, resolve } = queue.shift();
  speaking = true;
  let finished = false;
  const done = () => {
    if (finished) return;
    finished = true;
    speaking = false;
    resolve();
    pump();
  };

  const h = fnv(`${profile}|${text}`);
  if (bank && bank[h] && player) {
    player.src = `../voices/${h}.ogg`;
    player.onended = done;
    player.onerror = () => { if (!finished) speakTTS(text, profile, done); };
    player.play().catch(() => { if (!finished) speakTTS(text, profile, done); });
  } else {
    speakTTS(text, profile, done);
  }
}

/**
 * Queue a line. opts.profile: 'narrator' (default) | 'alien' | 'sound'.
 * opts.interrupt cancels anything queued or currently speaking first.
 * Resolves when spoken (immediately if speech is unavailable).
 */
export function say(text, opts = {}) {
  if (isMuted()) return Promise.resolve();
  if (opts.interrupt) stopSpeech();
  return new Promise((resolve) => {
    queue.push({ text, profile: opts.profile || 'narrator', resolve });
    pump();
  });
}

export function stopSpeech() {
  queue.forEach((q) => q.resolve());
  queue = [];
  speaking = false;
  if (player) {
    player.onended = null;
    player.onerror = null;
    try { player.pause(); } catch { /* not playing */ }
  }
  if ('speechSynthesis' in window) {
    try { window.speechSynthesis.cancel(); } catch { /* pre-gesture */ }
  }
}
